### ISSUE TITLE
Application icons are too big and go out of their bounding boxes

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#6]
All application icons in the task bar are too big, and every one with a different size, and some go outside it's box

**Comment by jmanc3** [comment]
**What GTK icon theme are you using?**

You can check the name in the **Icon Theme** tab using lxappearance or you can check the value of the line gtk-icon-theme-name in the file "~/.config/gtk-3.0/settings.ini"

**And can you send a screenshot?**

I think this is probably caused by the fact that some icon themes just link the same SVG icon for multiple sizes since they're supposed to be scalable to any size without losing quality, but last time I messed around with librsvg file loading, it didn't seem like there was a way to specify what size you wanted the image. Depending on the theme, it might be a PNG loading problem instead. I'll figure it out.

**Comment by jmanc3** [comment]
This might've been fixed in b9ba427, let me know.

**Comment by pushqrdx** [comment]
I am using the Adwaita, but it also happens with Breeze, and here's a screen show with mousepad, firefox and terminology 
![screenshot0](https://user-images.githubusercontent.com/25884937/119269248-4ae99580-bbbc-11eb-97b9-d6f6c15e1b39.png)

**Comment by jmanc3** [comment]
Try ab9fc4b for me. If it doesn't work right away, close winbar and then run the following commands
```bash
rm -r ~/.cache/c3_icon_cache; rm ~/.config/winbar/cached_icons/*
```

**Comment by pushqrdx** [comment]
weird, it isn't solved for me, still after removing all cache, icons are broken
![screenshot1](https://user-images.githubusercontent.com/25884937/119284014-48ab2980-bc04-11eb-804f-028ffaa62bbc.png)

**Comment by jmanc3** [comment]
Do you know what git commit icons started breaking for you or were they always broken?

**Comment by pushqrdx** [comment]
> Do you know what git commit icons started breaking for you or were they always broken?

@jmanc3 always broken, i just didn't get to report them initially

**Comment by pushqrdx** [comment]
hmmm idk what happened but using paper icons after a system restart stuff seem to be the correct size now.. i will close this and reopen if i face it again
